---
jobs:
- name: deploy
  plan:

  - get: release
    trigger: true
    params:
      include_source_tarball: true

  - get: common-tasks

  - task: cpanel-source
    file: common-tasks/extract-release-tarball.yaml
    output_mapping: {extracted: cpanel-source}

  - put: cpanel-docker-image
    params:
      build: cpanel-source
      tag: release/commit_sha
      additional_tags: release/tag

  - put: cpanel-auth0-client

  - get: cpanel-helm-config

  - task: decrypt-config
    file: common-tasks/decrypt-gitcrypt.yaml
    input_mapping: {encrypted: cpanel-helm-config}
    output_mapping: {decrypted: cpanel-helm-config}
    params:
      SYMMETRIC_KEY: ((secrets.gitcrypt-symmetric-key))

  - put: cpanel-helm-release
    params:
      chart: mojanalytics/cpanel
      values:
      - cpanel-helm-config/chart-env-config/((env))/cpanel.yml
      override_values:
      - { key: API.Image.Tag, path: release/commit_sha }
      - { key: API.Branch, value: master }
      - { key: tags.branch, value: false }
      - { key: API.Environment.OIDC_CLIENT_ID, path: cpanel-auth0-client/client_id }
      - { key: API.Environment.OIDC_CLIENT_SECRET, path: cpanel-auth0-client/client_secret }

resources:
- name: common-tasks
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-common-concourse-tasks.git

- name: release
  type: github-release
  source:
    owner: ministryofjustice
    repository: analytics-platform-control-panel
    access_token: ((secrets.github-access-token))

- name: cpanel-auth0-client
  type: auth0-client
  source:
    app-name: cpanel-master
    app-domain: ((secrets.services-domain))
    client-id: ((secrets.auth0-client-id))
    client-secret: ((secrets.auth0-client-secret))
    domain: ((secrets.auth0-domain))
    authz-url: ((secrets.auth0-authz-url))
    authz-audience: ((secrets.auth0-authz-audience))

- name: cpanel-docker-image
  type: docker-image
  source:
    repository: quay.io/mojanalytics/control-panel
    username: ((secrets.quay-username))
    password: ((secrets.quay-password))

- name: cpanel-helm-config
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-config.git

- name: cpanel-helm-release
  type: helm
  source:
    cluster_url: ((secrets.kubernetes-api-url))
    cluster_ca: ((secrets.kubernetes-ca-cert))
    helm_host: tiller-deploy.kube-system:44134
    token: ((secrets.kubernetes-token))
    namespace: default
    release: cpanel-master
    repos:
    - name: mojanalytics
      url: https://ministryofjustice.github.io/analytics-platform-helm-charts/charts

resource_types:
- name: auth0-client
  type: docker-image
  source:
    repository: quay.io/mojanalytics/concourse-auth0-resource
    tag: v0.1.1

- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.9.0
