apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "fullname" .}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.Frontend.Image.Repository }}:{{ .Values.Frontend.Image.Tag }}"
          imagePullPolicy: {{ .Values.Frontend.Image.PullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-client-secret
            - name: AUTH0_DOMAIN
              value: "{{ .Values.Frontend.Environment.AUTH0_DOMAIN }}"
            - name: ENV
              value: "{{ .Values.Frontend.Environment.ENV }}"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: sentry-dsn
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
