apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
type: Opaque
data:
  api-user: {{ .Values.Frontend.Environment.API_USER | b64enc | quote }}
  api-password: {{ .Values.Frontend.Environment.API_PASSWORD | b64enc | quote }}
