apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
type: Opaque
data:
  auth0-client-id: {{ .Values.Frontend.Environment.AUTH0_CLIENT_ID | b64enc | quote }}
  auth0-client-secret: {{ .Values.Frontend.Environment.AUTH0_CLIENT_SECRET | b64enc | quote }}
  sentry-dsn: {{ .Values.Frontend.Environment.SENTRY_DSN | b64enc | quote }}
