apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        kubernetes.io/cluster-service: "true"
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
        - key: dedicated
          effect: NoSchedule
          value: highmem
      serviceAccountName: {{ template "fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: FLUENTD_ARGS
            value: --no-supervisor -q
          - name:  FLUENT_ELASTICSEARCH_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_host
          - name:  FLUENT_ELASTICSEARCH_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_port
          - name:  FLUENT_ELASTICSEARCH_SCHEME
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_scheme
          - name:  FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_logstash_prefix
          {{ if .Values.elasticsearch.username }}
          - name: FLUENT_ELASTICSEARCH_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_username
          {{ end }}
          {{ if .Values.elasticsearch.password }}
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: elasticsearch_password
          {{ end }}

        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentdconf
          mountPath: /etc/fluent/config.d
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentdconf
        configMap:
          name: {{ template "fullname" . }}
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
