ServicesDomain: ""
Frontend:
  Branch: "master"
  Image:
    Repository: quay.io/mojanalytics/control-panel-frontend
    Tag: 0.1.0
    PullPolicy: Always
  Environment:
    API_URL: "http://cpanel-master-cpanel"
    AUTH0_CLIENT_ID: ""
    AUTH0_CLIENT_SECRET: ""
    AUTH0_DOMAIN: ""
    ENV: ""
    SENTRY_DSN: ""
