apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    type: cron
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.image }}"
            env:
            - name: LABEL_SELECTOR
              value: '{{ .Values.labelSelector }}'
            - name: RSTUDIO_ACTIVITY_CPU_THRESHOLD
              value: '{{ .Values.cpuActivityThreshold }}'
          restartPolicy: Never
