---
remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
  - charts
excluded-charts:
  # - common
  # - common-test
chart-repos:
  # - bitnami=https://charts.bitnami.com/bitnami
  - analytics-platform-helm-charts=https://analytical-platform-charts.github.io/charts
