## apply this only on one upgrade - like a database migration
apiVersion: batch/v1
kind: Job
metadata:
  name: annotate-airflow-ns
  namespace: kube-system
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This hook depends on helm creating the target namespace if it doesn't exist
    # before the hook is called. This is the case on Helm >v2.9.1
    {{ if eq .Chart.Version "0.0.3" }}
    helm.sh/hook: pre-install,pre-upgrade
    {{ else }}
    helm.sh/hook: pre-install
    {{ end }}
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: annotator
        image: gcr.io/google_containers/hyperkube:v1.11.7
        imagePullPolicy: "IfNotPresent"
        restartPolicy: Never
        command:
        - kubectl
        - annotate
        - --overwrite
        - ns
        - {{ .Release.Namespace }}
        - |
            iam.amazonaws.com/allowed-roles=[{{ .Values.kube2iam.allowedRoles | quote }}]
      serviceAccountName: {{ .Values.kube2iam.serviceAccountName }}
