apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-{{ randAlphaNum 5 | lower }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
spec:
  template:
    spec:
      containers:
        - name: reset-user-home
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name : home
              mountPath: "/home/{{ .Values.Username }}"
          command:
            - /bin/sh
            - -c
            - |
              rm -rf /home/{{ .Values.Username }}/.rstudio.bak &&
              rm -rf /home/{{ .Values.Username }}/.rstudio &&
              rm -rf /home/{{ .Values.Username }}/.conda.bak/ &&
              rm -rf /home/{{ .Values.Username }}/.conda/ &&
              rm -rf /home/{{ .Values.Username }}/.condarc.bak &&
              rm -rf /home/{{ .Values.Username }}/.condarc &&
              rm -rf /home/{{ .Values.Username }}/R/library/*
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: nfs-home

      restartPolicy: OnFailure
  backoffLimit: 5
