{{- if .Values.rstudio.renviron.mount -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: renviron
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
data:
  .Renviron: |
    AWS_ROLE_ARN=arn:aws:iam::{{ .Values.aws.accountID }}:role/{{ .Values.aws.iamRole }}
    AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
{{- end -}}
