apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
data:
  chown_home.sh: |
    #!/usr/local/bin/bash -eu
    if [[ $( stat -c %u /home/{{ .Values.username }} ) -ne 1000 ]];then
      chown -R 1000 /home/{{ .Values.username }}
    fi
