apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "unidle_key" . }}
    unidler-key: {{ template "unidle_key" . }}
    "mojanalytics.xyz/idleable": "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        "mojanalytics.xyz/idleable": "true"
      annotations:
        iam.amazonaws.com/role: {{ .Values.aws.iamRole }}
    spec:
      priorityClassName: {{ .Chart.Name }}
      serviceAccountName: {{ .Values.username }}-rstudio
      initContainers:
        # Use the init contianer to check if the home directory has the correct user permissions of 1000
        # We don't mind which group the home has as it can be both staff and
        - name: init
          image: "bash:5.1"
          imagePullPolicy: {{ .Values.rstudio.image.pullPolicy }}
          command: [/chown_home.sh]
          volumeMounts:
            - name: configmap
              mountPath: /chown_home.sh
              subPath: chown_home.sh
            - name: home
              mountPath: "/home/{{ .Values.username }}"
      containers:
        - name: rstudio-auth-proxy
          image: "{{ .Values.authProxy.image.repository }}:{{ .Values.authProxy.image.tag }}"
          imagePullPolicy: {{ .Values.authProxy.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: {{ .Values.authProxy.express.port }}
          env:
            - name: TARGET_URL
              value: http://localhost:{{ .Values.rstudio.port }}
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: domain
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_id
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: callback_url
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_secret
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_secret
            - name: USER
              value: {{ .Values.username }}
            - name: RSTUDIO_ADD_SECURE_COOKIE
              value: "true"
            - name: RSTUDIO_SECURE_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secure_cookie_key
            - name: COOKIE_MAXAGE
              value: "{{ .Values.authProxy.cookieMaxAge }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: proxy
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: proxy
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
{{ toYaml .Values.authProxy.resources | indent 12 }}

        - name: r-studio-server
          image: "{{ .Values.rstudio.image.repository }}:{{ .Values.rstudio.image.tag }}"
          imagePullPolicy: {{ .Values.rstudio.image.pullPolicy }}
          ports:
            - name: rstudio
              containerPort: {{ .Values.rstudio.port }}
          env:
            - name: USER
              value: "{{ .Values.username }}"
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: aws_default_region
            - name: SECURE_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secure_cookie_key
          readinessProbe:
            httpGet:
              path: /
              port: rstudio
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: rstudio
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: home
              mountPath: "/home/{{ .Values.username }}"
          resources:
{{ toYaml .Values.rstudio.resources | indent 12 }}

      volumes:
        - name: configmap
          configMap:
            name: {{ .Release.Name }}
            defaultMode: 0500
        - name: home
          persistentVolumeClaim:
            claimName: nfs-home
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
