apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
      annotations:
        iam.amazonaws.com/role: {{ .Values.aws.iamRole }}
    spec:
      containers:

        - name: rstudio-auth-proxy
          image: "{{ .Values.authProxy.image.repository }}:{{ .Values.authProxy.image.tag }}"
          imagePullPolicy: {{ .Values.authProxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.authProxy.express.port }}
          env:
            - name: USER
              value: {{ .Values.username }}
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_id
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: domain
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: callback_url
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_secret
            - name: SECURE_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secure_cookie_key
            - name: PROXY_TARGET_HOST
              value: localhost
            - name: PROXY_TARGET_PORT
              value: "{{ .Values.rstudio.port }}"
            - name: EXPRESS_HOST
              value: {{ .Values.authProxy.express.host }}
            - name: EXPRESS_PORT
              value: "{{ .Values.authProxy.express.port }}"
          readinessProbe:
            httpGet:
              path: /login?healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
{{ toYaml .Values.authProxy.resources | indent 12 }}

        - name: r-studio-server
          image: "{{ .Values.rstudio.image.Repository }}:{{ .Values.rstudio.image.tag }}"
          imagePullPolicy: {{ .Values.rstudio.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.rstudio.port }}
          env:
            - name: USER
              value: {{ .Values.username }}
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: aws_default_region
            - name: SECURE_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secure_cookie_key
            - name: TOOLS_DOMAIN
              value: {{ .Values.toolsDomain }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: home
              mountPath: "/home/{{ .Values.username }}"
          resources:
{{ toYaml .Values.rstudio.resources | indent 12 }}

      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: nfs-home
