apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
type: Opaque
data:
  client_secret: {{ .Values.proxy.auth0.clientSecret | b64enc | quote }}
  client_id: {{ .Values.proxy.auth0.clientId | b64enc | quote }}
  domain: {{ .Values.proxy.auth0.domain | b64enc | quote }}
  aws_default_region: {{ .Values.aws.defaultRegion | b64enc | quote }}
