apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "control-panel.services.{{ .Values.ToolsDomain }}"
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
        path: /
