
replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: 7.9.1
  pullPolicy: IfNotPresent
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

service:
  port: 80

ingress:
  enabled: true
  addTlsBlock: true

config:

  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: ["${ELASTICSEARCH_URL}"]
    xpack.monitoring.elasticsearch.username: '${ELASTICSEARCH_USER}'
    xpack.monitoring.elasticsearch.password: '${ELASTICSEARCH_PASSWORD}'
    log.level: debug
