apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    app: {{ include "auth-user-exports.app_name" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: API_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}
                      key: auth0_domain
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}
                      key: auth0_client_id
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}
                      key: auth0_client_secret
                - name: ENV
                  value: {{ .Values.env.env }}
                - name: ROLE_ARN
                  value: {{ .Values.env.role_arn | quote }}
                - name: BUCKET
                  value: {{ .Values.env.bucket }}
          restartPolicy: OnFailure
