apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "logstash.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "logstash.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          env:
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: elasticsearch_url
            - name: ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: elasticsearch_user
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: elasticsearch_password
            - name: ELASTICSEARCH_INDEX
              value: {{ .Values.elasticsearch.index }}
            - name: LOGSTASH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: logstash_user
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: logstash_password
            - name: LOGSTASH_PORT
              value: "{{ .Values.image.port }}"
          volumeMounts:
            - name: pipelines
              mountPath: /usr/share/logstash/pipeline
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: pipelines
          configMap:
            name: {{ .Release.Name }}-pipelines
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
