apiVersion: batch/v1
kind: Job
metadata:
  name: create-user-home-{{ .Values.Username }}
  namespace: default
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: create-user-home
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: ubuntu
        image: ubuntu:16.04
        command: ["/bin/sh", "-c",
          "useradd -u 1001 -g staff -m -d /homes/{{ .Values.Username }} {{ .Values.Username }}"]
        volumeMounts:
          - name: homes
            mountPath: "/homes"
      restartPolicy: Never
      volumes:
      - name: homes
        persistentVolumeClaim:
          claimName: nfs-homes
