apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-home-{{ .Values.Username }}
  # No namespace, PVs are global
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Mi
  mountOptions:
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.EFSHostname }}
    path: /
  claimRef:
    name: efs-home
    namespace: user-{{ .Values.Username }}