apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-home
  namespace: user-{{ .Values.Username }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
