kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-home
  namespace: user-{{ .Values.Username }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      mounttype: user
      user: {{ .Values.Username }}
  resources:
    requests:
      storage: 10Gi
