apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-{{ .Values.Username }}
  namespace: user-{{ .Values.Username }}
spec:
  hard:
    persistentvolumeclaims: "2"
    requests.storage: "15Gi"
# Allows only 1 volume claim of up to 15GB in user's namespace
