apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-{{ .Values.Username }}
  namespace: user-{{ .Values.Username }}
spec:
  hard:
    persistentvolumeclaims: "2"
    requests.storage: "20Gi"
# Allows up to 2 volume claims that both equal up to 20GB in user's namespace
