apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-{{ .Values.Username }}
  namespace: user-{{ .Values.Username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin # Does not allow user to modify resource quotas or the namespace itself
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.Username }}