# environment to target, e.g. "dev"
env: ""

# S3 Bucket where archived data will be moved to
archiveBucket: ""

# IAM role assumed by the buckets-archiver
iamRole: ""

# Docker image version
image:
  repository: quay.io/mojanalytics/buckets-archiver
  tag: v0.0.1
  pullSecrets: []

# Schedule when to run
#   min    hour   day    month (Sun-Sat)
# "(0-59) (0-23) (1-31) (1-12) (0-6)"
# See https://kubernetes.io/docs/user-guide/cron-jobs/#schedule
schedule: "*/5 * * * *" # every 5 minutes

# Concurrency Policy
# Allow|Forbid|Replace
# See https://kubernetes.io/docs/user-guide/cron-jobs/#concurrency_policy
concurrencyPolicy: Forbid

# The number of failed finished jobs to retain.
failedJobsHistoryLimit: 5

# AWS default region
awsDefaultRegion: "eu-west-1"
