ToolsDomain: dev.mojanalytics.xyz
API:
  Image:
    Repository: quay.io/mojanalytics/control-panel
    Tag: 0.1.0
    PullPolicy: Always
  Environment:
    DB_HOST: dev-control-panel-db.cyfs8aeszqyh.eu-west-1.rds.amazonaws.com
