# Docker image
image:
  name: quay.io/mojanalytics/unidler
  tag: v0.1.0
  pullPolicy: Always

logLevel: INFO

replicaCount: 1

service:
  externalPort: 80
  internalPort: 8080
  type: ClusterIP

servicesDomain: ""
