# Docker image
image:
  name: quay.io/mojanalytics/go-unidler
  tag: v0.1.0
  pullPolicy: IfNotPresent

replicaCount: 3

ingress:
  addTlsBlock: true
  className: "nginx"

service:
  externalPort: 80
  internalPort: 8080
  type: ClusterIP

servicesDomain: ""
