toolsDomain: "tools.EXAMPLE.COM"
Username: ""
airflow:
  secretKey: ""
  fernetKey: ""
  image:
    repository: "quay.io/mojanalytics/airflow"
    tag: "1.10.10"
    pullPolicy: "IfNotPresent"
    port: "8080"
  config:
    core:
      parallelism: "1"
    webserver:
      enable_proxy_fix: "True"
  resources:
    limits:
      cpu: 250m
      memory: 8Gi
    requests:
      cpu: 250m
      memory: 8Gi
service:
  port: 80
authProxy:
  image: "quay.io/mojanalytics/auth-proxy"
  tag: "v5.2.6"
  imagePullPolicy: "IfNotPresent"
  containerPort: "3000"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  auth0_domain: ""
  auth0_client_id: ""
  auth0_client_secret: "" # put dummy value here to stop helm lint complaining
  cookie_maxage: 36000
aws:
  iamRole: ""
  defaultRegion: "eu-west-1"
cookie_secret: ""
kube2iam:
  allowedRoles: ".*"
  serviceAccountName: ""
image:
  pullSecrets: []
