apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "patch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "patch", "watch"]

  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["list"]
