apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.servicesDomain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
        path: /
