{{- $chart_fullname := cat .Chart.Name .Chart.Version | replace " " "-" -}}
{{- range $key, $val := .Values }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key | snakecase | replace "_" "-" }}
  namespace: concourse-admin
  labels:
    chart: {{ $chart_fullname }}
type: Opaque
data:
  {{- range $name, $secret := $val }}
  {{ $name | snakecase | replace "_" "-" }}: {{ $secret | b64enc | quote }}
  {{- end }}
{{- end }}
