{{- range $key, $val := .Values }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- range $name, $secret := $val }}
  {{ $name }}: {{ $secret | b64enc | quote }}
  {{- end }}
{{- end }}
