apiVersion: v1
appVersion: 1.12.3
description: Scales worker nodes within autoscaling groups
name: cluster-autoscaler
version: 1.0.0
sources:
- https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
- https://github.com/spotinst/kubernetes-autoscaler/tree/master/cluster-autoscaler
