apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
    verbs:
      - "create"
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "list"
