apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Chart.Name }}"
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: "{{ .Chart.Name }}"
  kind: ClusterRole
subjects:
  - apiGroup: ""
    name: "{{ .Chart.Name }}"
    kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"

# This allows a service account in the Release's namespace (i.e. default) to manage resources in the kube-system namespace
