apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.django.port }}
    protocol: TCP
  selector:
    app: "{{ .Chart.Name }}"
  sessionAffinity: ClientIP
