apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
