---
jobs:
- name: update-org-pipelines
  plan:
  - get: org
    trigger: true
  - put: org

resources:
- name: org
  type: github-org
  check_every: 24h
  source:
    name: ((github-org))
    team_name: ((team_name))
    concourse_url: ((concourse_url))
    username: ((fly.username))
    password: ((fly.password))
    access_token: ((github-access-token))
  webhook_token: ((github-webhook-token))

resource_types:
- name: github-org
  type: docker-image
  source:
    repository: ((github-org-resource-image))
    tag: ((github-org-resource-tag))
