NFSHostname: ""
Username: ""
Email: ""
Fullname: ""
Env: ""
OidcDomain: ""

ubuntu:
  image: 593291632749.dkr.ecr.eu-west-1.amazonaws.com/ubuntu:16.04

EFSHostname: "fs-44e44970.efs.eu-west-1.amazonaws.com"
