# Calico Version v2.2.1
# https://docs.projectcalico.org/v2.2/releases#v2.2.1
# This manifest includes the following component versions:
#   calico/ctl:v1.2.1

apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  {{- with .Values.image.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
    - name: {{ . }}
  {{- end }}
  {{- end }}
  hostNetwork: true
  containers:
  - name: calicoctl
    image: quay.io/calico/ctl:v1.2.1
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    env:
    - name: ETCD_ENDPOINTS
      valueFrom:
        configMapKeyRef:
          name: calico-config
          key: etcd_endpoints
