apiVersion: batch/v1
kind: Job
metadata:
  name: cpanelapi-pipeline
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: set-pipeline
    spec:
      containers:
      - name: set-pipeline
        image: appropriate/curl:3.1
        imagePullPolicy: IfNotPresent
        env:
          - name: CONCOURSE_TEAM
            value: {{ .Values.concourse.team }}
          - name: CONCOURSE_URL
            value: {{ .Values.concourse.externalURL }}
          - name: ENV
            value: {{ .Values.env }}
          - name: FLY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fly
                key: password
          - name: FLY_USERNAME
            valueFrom:
              secretKeyRef:
                name: fly
                key: username
          - name: GITHUB_WEBHOOK_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: github-webhook-token
        command: [ "/bin/sh" ]
        args:
          - /scripts/set-pipeline.sh
          - cpanel-api
        volumeMounts:
          - name: scripts
            mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 500
