Name: ""
BaseHost: ""
GithubRepo: ""
SlackToken: ""
Port: 80
Image:
  Repository: ""
  Tag: ":latest"
  PullPolicy: Always
env:
  AUTH0_AUTHZ_AUDIENCE: ""
  AUTH0_AUTHZ_URL: ""
  AUTH0_CLIENT_ID: ""
  AUTH0_CLIENT_SECRET: ""
  AUTH0_DOMAIN: ""
