apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
    host: {{ include "unidle_key" . }}
    unidle-key: {{ include "unidle_key" . }}
    "mojanalytics.xyz/idleable": "true"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        "mojanalytics.xyz/idleable": "true"
      annotations:
        iam.amazonaws.com/role: {{ .Values.aws.iamRole }}
    spec:
      priorityClassName: {{ .Chart.Name }}
      serviceAccountName: {{ .Values.Username }}-jupyter
      containers:
        - name: {{ .Chart.Name }}-auth-proxy
          image: {{ .Values.authProxy.image }}:{{ .Values.authProxy.tag }}
          imagePullPolicy: {{ .Values.authProxy.imagePullPolicy }}
          ports:
            - name: proxy
              containerPort: {{ .Values.authProxy.containerPort }}
          env:
            - name: TARGET_URL
              value: http://localhost:{{ .Values.jupyter.containerPort }}
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0_domain
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0_client_id
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0_callback_url
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0_client_secret
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_secret
            - name: USER
              value: "{{ .Values.Username }}"
            - name: COOKIE_MAXAGE
              value: {{ .Values.authProxy.cookie_maxage | quote }}
            - name: TUNNEL_ENABLED
              value: {{ .Values.authProxy.tunnel.enabled | quote }}
            - name: TUNNEL_PORT_RANGE
              value: {{ .Values.authProxy.tunnel.port_range | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: proxy
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: proxy
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
{{ toYaml .Values.authProxy.resources | indent 12 }}
        - name: {{ .Chart.Name }}
          image: {{ .Values.jupyter.image }}:{{ .Values.jupyter.tag }}
          imagePullPolicy: {{ .Values.jupyter.imagePullPolicy }}
          ports:
            - name: jupyter
              containerPort: {{ .Values.jupyter.containerPort }}
          command:
            - "start-notebook.sh"
          args:
            - "--NotebookApp.token=''"
            - --ContentsManager.allow_hidden=True
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "1"
          readinessProbe:
            httpGet:
              path: /
              port: jupyter
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: jupyter
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: efs-home
              mountPath: /home/jovyan
              subPath: {{.Values.username}}/jupyter
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }}
      volumes:
        - name: efs-home
          persistentVolumeClaim:
            claimName: efs-home
