apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.Username }}-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
