apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    type: cron
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        spec:
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
          {{- range . }}
            - name: {{ . }}
          {{- end }}
          {{- end }}
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: failed-pods-cleaner
            image: "{{ .Values.image.value }}"
            command:
            - "scripts/pod_cleaner.sh"
            env:
            - name: POD_CLEANER_PHASE
              value: Failed
            - name: POD_CLEANER_DAYS
              value: '{{ .Values.deleteFailedAfter }}'
            volumeMounts:
              - name: {{ .Release.Name }}
                mountPath: "/scripts"
          - name: pending-pods-cleaner
            image: "{{ .Values.image.value }}"
            command:
            - "scripts/pod_cleaner.sh"
            env:
            - name: POD_CLEANER_PHASE
              value: Pending
            - name: POD_CLEANER_DAYS
              value: '{{ .Values.deletePendingAfter }}'
            volumeMounts:
              - name: {{ .Release.Name }}
                mountPath: "/scripts"
          - name: succeeded-pods-cleaner
            image: "{{ .Values.image.value }}"
            command:
            - "scripts/pod_cleaner.sh"
            env:
            - name: POD_CLEANER_PHASE
              value: Succeeded
            - name: POD_CLEANER_DAYS
              value: '{{ .Values.deleteSucceededAfter }}'
            volumeMounts:
              - name: {{ .Release.Name }}
                mountPath: "/scripts"
          restartPolicy: Never
          volumes:
          - name: {{ .Release.Name }}
            configMap:
              name: {{ .Release.Name }}
              defaultMode: 0555 # a+rx
