username: ""
toolsDomain: "tools.EXAMPLE.COM"
image:
  pullSecrets: []
aws:
  iamRole: ""
  defaultRegion: "eu-west-1"
authProxy:
  appProtocol: "https"
  auth0:
    clientSecret: ""
    clientId: ""
    domain: "AUTH0_USER.eu.auth0.com"
  cookieMaxAge: "28800" # 8 hours in seconds
  cookieSecret: ""
  express:
    host: "0.0.0.0"
    port: 3000
  image:
    repository: quay.io/mojanalytics/auth-proxy
    tag: "v5.2.6"
    pullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
rstudio:
  secureCookieKey: ""
  port: "8787"
  image:
    repository: quay.io/mojanalytics/rstudio
    tag: "1.2.1335-r3.5.1-python3.7.1-conda-10"
    pullPolicy: "IfNotPresent"
    # init option allows you to run an init container that does the setup of the conda environment
    # this is quite slow and if it was run as part of the main container then it would cause problems.
    # This exists here because you might want to downgrade to an older image, which doesn't take the arg
    # to the ./start.sh script
    init: true
  resources:
    limits:
      cpu: 1.5
      memory: 12Gi
    requests:
      cpu: 1.5
      memory: 12Gi
