apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
