apiVersion: v1
kind: Secret
metadata:
  name: org-pipeline-{{ .Values.github.org }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  fly-password: {{ .Values.concourse.password | b64enc | quote }}
  fly-username: {{ .Values.concourse.username | b64enc | quote }}
  github-access-token: {{ .Values.github.accessToken | b64enc | quote }}
  github-webhook-token: {{ .Values.github.webhookToken | b64enc | quote }}
  kubernetes-ca-cert: {{ .Values.kubernetes.caCert | b64enc | quote }}
  kubernetes-token: {{ .Values.kubernetes.token | b64enc | quote }}
