# Docker image version
image: quay.io/mojanalytics/idler:v0.5.2

# Schedule when to run
#   min    hour   day    month (Sun-Sat)
# "(0-59) (0-23) (1-31) (1-12) (0-6)"
# See https://kubernetes.io/docs/user-guide/cron-jobs/#schedule
schedule: "0 22 * * *"

# Concurrency Policy
# Allow|Forbid|Replace
# See https://kubernetes.io/docs/user-guide/cron-jobs/#concurrency_policy
concurrencyPolicy: Forbid

labelSelector: 'app=rstudio'

logLevel: 'INFO'

# percentage of a CPU in the last minute which marks an active instance
# (which should not be idled)
cpuActivityThreshold: 10
