apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    repo: "{{ .Values.GithubRepo }}"
    app: {{ template "fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: hubot
          image: "{{ .Values.Image.Repository }}:{{ .Values.Image.Tag | replace ":" "" }}"
          imagePullPolicy: {{ .Values.Image.PullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: AUTH0_AUTHZ_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-authz-audience
            - name: AUTH0_AUTHZ_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-authz-url
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-client-secret
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: auth0-domain
            - name: HUBOT_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: slack_token
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /hubot/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hubot/ready
              port: http
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 60
          resources:
            requests:
              cpu: 10m
          volumeMounts:
            - name: varlognginx
              mountPath: /var/log/nginx

      volumes:
        - name: varlognginx
          emptyDir: {}
