apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  slack_token: {{ .Values.SlackToken | b64enc | quote }}
