apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  auth0-authz-audience: {{ .Values.env.AUTH0_AUTHZ_AUDIENCE | b64enc | quote }}
  auth0-authz-url: {{ .Values.env.AUTH0_AUTHZ_URL | b64enc | quote }}
  auth0-client-id: {{ .Values.env.AUTH0_CLIENT_ID | b64enc | quote }}
  auth0-client-secret: {{ .Values.env.AUTH0_CLIENT_SECRET | b64enc | quote }}
  auth0-domain: {{ .Values.env.AUTH0_DOMAIN | b64enc | quote }}
  slack_token: {{ .Values.SlackToken | b64enc | quote }}
