apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    repo: "{{ .Values.GithubRepo }}"
    app: {{ template "fullname" . }}
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
