---
name: "Charts: Lint and test"

"on":
  pull_request:
    paths:
      - "charts/**"
      - "!charts/**/README.md"
      - .github/workflows/charts-lint-test.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}
      common: ${{ steps.list-changed.outputs.common }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          changed_unfiltered=$(ct list-changed --config .github/ct.yaml --excluded-charts "")
          if [[ $(grep -E "^charts/common(-test)?$" <<< "$changed_unfiltered") ]]; then
            echo "::set-output name=common::true"
          fi
      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config .github/ct.yaml --excluded-charts ""
        if: steps.list-changed.outputs.changed == 'true' || steps.list-changed.outputs.common == 'true'

      - name: Output
        id: chart-testing-output
        uses: actions/github-script@v3
        # if: steps.list-changed.outputs.changed == 'true' || steps.list-changed.outputs.common == 'true'
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Chart Testing Output 🖌\`${{ steps.lint.outcome }}\`

            **Pusher**: @${{ github.actor }}
            **Action**: ${{ github.event_name }}
            `;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  # Don't install into KIND right now
  # Our charts or not currently compatible with newer version of Kubernetes
  # install:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Install Helm
  #       uses: azure/setup-helm@v1
  #       with:
  #         version: v3.4.0
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9
  #     - name: Set up chart-testing
  #       uses: helm/chart-testing-action@v2.0.1
  #     - name: Create kind cluster
  #       uses: helm/kind-action@v1.1.0
  #       if: needs.lint.outputs.changed == 'true' || needs.lint.outputs.common == 'true'
  #     - name: Run chart-testing (install)
  #       run: ct install --config .github/ct.yaml
  #       if: needs.lint.outputs.changed == 'true'
